/*
 * @author Jeffrey Chan & Minyi Li, RMIT 2020
 */
package solver;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import grid.SudokuGrid;


/**
 * Algorithm X solver for standard Sudoku.
 */
public class AlgorXSolver extends StdSudokuSolver
{
	// prepare the object to store matrix, partial solutions and the columns deleted
	List<Matrix> matrixes = null;
	List<Matrix> solutions = new ArrayList<>();
	List<Integer> deletedColumns = new ArrayList<>();
	Integer size = null;
	
    public AlgorXSolver() {
    } // end of AlgorXSolver()


    /**
     * The public solve method for other programs to call
     */
    @Override
    public boolean solve(SudokuGrid sudokuGrid) {
    	
    	int numConstraints = 4;
    	
    	// if the matrix is empty, it need to be generated by the size of sudoku grid and symbols and the number of constraints.
    	if (matrixes == null)
    		matrixes = MatrixUtils.generateMatrix(sudokuGrid.size, sudokuGrid.sqrt, sudokuGrid.symbols, numConstraints, null);
    	
    	// As some cells have been inserted value, 
    	// we need to get rid of those rows and columns related to them in the matrix 
    	removeRowsByGrid(sudokuGrid);
    	
    	// the total number of constraints need to be satisfied in the matrix
    	size = sudokuGrid.size*sudokuGrid.size*numConstraints;
    	
    	// call the private solve method to find the solution of the standard sudoku
    	if (solve(matrixes, deletedColumns)) {
    		// After finding the solutions, 
    		// add the value to each cell of the standard sudoku grind.
    		for (Matrix matrix : solutions) {
    			sudokuGrid.grid[matrix.row][matrix.col] = matrix.value;
    		}
    		return true;
    	}

        return false;
    } // end of solve()
    
    
    /**
     * The exact method to solve standard sudoku problem
     * @param matrixes the matrixes to analyse
     * @param deletedColumns those deleted columns of constraints in matrix
     * @return the problem is solved or not.
     */
	@SuppressWarnings("unchecked")
	private Boolean solve(List<Matrix> matrixes, List<Integer> deletedColumns) {
		
		// If Matrix is empty, the problem is solved; terminate successfully.
		if (matrixes.size() == 0) {
			return true;
		}
		
		// Find the minimize sum of column constraints in the current matrix
		// and get the matrixes of potential solution
		Map<String, Object> minMap = findMinSumByColumn(matrixes, deletedColumns);
		List<Matrix> potentialSols = (List<Matrix>) minMap.get("potentialSols");

		// If the index is null, it means that it cannot find a solution based on the current situation.
		if (minMap.get("idx") == null) {
			return false;
		}
		
		// If the min value is 0, then the size of potential solution will be 0,
		// which means the process is terminated unsuccessfully.
		if (potentialSols.size() == 0) {
			return false;
		}
		
		// To store the current matrix and deleted columns for backtracking recovery
		List<Matrix> tempmatrixes = new ArrayList<>();
		tempmatrixes.addAll(matrixes);
		List<Integer> tempDeletedColumns = new ArrayList<>();
		tempDeletedColumns.addAll(deletedColumns);
		
		for (Matrix matrix : potentialSols) {
			// add the partial solutions
			solutions.add(matrix);
			
			// find which columns should be deleted
			for (int i = 0; i < matrix.constraints.length; i++) {
				if (matrix.constraints[i] != null && matrix.constraints[i] == 1) {
					deletedColumns.add(i);
				}
			}
			
			// remove matrix based on the deleted columns
			for (Integer i : deletedColumns) {
				// delete row by idx
				matrixes.removeIf(x->x.constraints[i] != null);
			}
			
			// Use the modified matrix to find partial solutions recursively.
			if (solve(matrixes, deletedColumns)) {
				return true;
				
			// if it returns false, it means that the partial solution is wrong,
			// and the process need to be recovered to the previous state, which is backtracking.
			}else {
				solutions.remove(matrix);
				matrixes.removeAll(matrixes);
				matrixes.addAll(tempmatrixes);
				deletedColumns.removeAll(deletedColumns);
				deletedColumns.addAll(tempDeletedColumns);
			}
		}
		
		return false;
	}
    
	
	/**
	 * The method is used to find the minimize sum of columns in the current matrix
	 * and based on the column, prepare to matrixes which are potential solutions.
	 * 
	 * @param matrixes the current matrix
	 * @param deletedColumns the column deleted
	 * @return
	 */
    private Map<String, Object> findMinSumByColumn(List<Matrix> matrixes, List<Integer> deletedColumns) {
		
		Integer[] sum = new Integer[size]; 
		Integer min = null;
		Integer idx = null;
	
		for (Matrix m : matrixes) {
			for (int i = 0; i < size; i++) {
				if (m.constraints[i] != null) {
					if (sum[i] == null) 
						sum[i] = 0;
					sum[i] = sum[i] + m.constraints[i];
				}
			}
		}
		
		
		for (int i = 0; i < size; i++) {
			// if the index of column can be found in the list of deleted columns
			// it means that the column should be skipped.
			if (deletedColumns.contains(i)) {
				continue;
			}
			if (sum[i] == null) {
				idx = i;
				break;
			}
			if (min == null || min > sum[i]) {
				min = sum[i];
				idx = i;
			}
		}
		
		List<Matrix> potentialSols = new ArrayList<>();
		
		if (min != null) {
			for (Matrix m : matrixes) {
				if (m.constraints[idx] != null) {
					potentialSols.add(m);
				}
			}
		}
		
		Map<String, Object> minMap = new HashMap<>();
		minMap.put("potentialSols", potentialSols);
		minMap.put("idx", idx);
		
		assert(idx == null);
		
		return minMap;
	}
    
    
    /**
     * Remove the rows and columns if the cell contains a value
     * @param sudokuGrid the sudoku grid
     */
    private void removeRowsByGrid(SudokuGrid sudokuGrid) {
    	
    	for (int i = 0; i < sudokuGrid.size; i++) {
    		for (int j = 0; j < sudokuGrid.size; j++) {
    			if (sudokuGrid.grid[i][j] != null) {
    				// delete row by idx
    				for (Matrix m : matrixes) {
    					if (m.row == i && m.col == j && m.value == sudokuGrid.grid[i][j]) {
    						matrixes.remove(m);
    						
    						for (int k = 0; k < m.constraints.length; k++) {
    	    					if (m.constraints[k] != null && m.constraints[k] == 1) {
    	    						deletedColumns.add(k);
    	    					}
    	    				}

    	    				for (Integer n : deletedColumns) {
    	    					// delete row by idx
    	    					matrixes.removeIf(x->x.constraints[n] != null);
    	    				}
    						
    						break;
    					}
    				}
    			}
    		}
    	}
	}

} // end of class AlgorXSolver
