/*
 * @author Jeffrey Chan & Minyi Li, RMIT 2020
 */

package solver;

import java.util.ArrayList;
import java.util.List;

import grid.SudokuGrid;


/**
 * Dancing links solver for standard Sudoku.
 */
public class DancingLinksSolver extends StdSudokuSolver
{
	// prepare the object to store matrix, partial solutions, the columns deleted and header nodes
	List<Matrix> matrixes = null;
	List<DLXNode> solutions = new ArrayList<>();
	List<Integer> deletedColumns = new ArrayList<>();
	Integer size = null;
	List<HeaderNode> headerNodes = new ArrayList<>();

    public DancingLinksSolver() {
    } // end of DancingLinksSolver()


    /**
     * The public solve method for other programs to call
     * @param the sudoku grid
     */
    @Override
    public boolean solve(SudokuGrid sudokuGrid) {
    	
    	int numConstraints = 4;
    	
    	// if the matrix is empty, it need to be generated by the size of sudoku grid and symbols and the number of constraints.
    	if (matrixes == null)
    		matrixes = MatrixUtils.generateMatrix(sudokuGrid.size, sudokuGrid.sqrt, sudokuGrid.symbols, numConstraints, null);

    	// As some cells have been inserted value, 
    	// we need to get rid of those rows and columns related to them in the matrix 
    	removeRowsByGrid(sudokuGrid);
    	
    	size = sudokuGrid.size*sudokuGrid.size*numConstraints;
    	
    	// use the matrix to generate a dancing link board
    	HeaderNode masterNode = this.makeDLXBoard(matrixes);
    	
    	// call the private solve method to find the solution of the standard sudoku
    	if (solve(masterNode)) {
    		// After finding the solutions, 
    		// add the value to each cell of the standard sudoku grind.
    		for (DLXNode cell : solutions) {
    			sudokuGrid.grid[cell.row][cell.col] = cell.value;
    		}
    		return true;
    	}

        // placeholder
        return false;
    } // end of solve()
    
    
    /**
     * The exact method to solve standard sudoku problem
     * @param masterNode the master node to start the process
     * @return the problem is solved or not.
     */
    private Boolean solve(HeaderNode masterNode) {

    	// If it is back to the master node, terminated successfully.
		if(masterNode.rightNode == masterNode) {
			return true;
		}
		
		// Find the minimize sum of column node in the current matrix
		HeaderNode targetNode = this.findColNodeWithMinSize(masterNode);
		
		// If the min value is 0, then the size of potential solution will be 0,
		// which means the process is terminated unsuccessfully.
		if (targetNode.size == 0) {
			return false;
		}
		
		// cover column node
		targetNode.coverNodes();
		
		// cover row nodes based on the column node
		DLXNode pointerNode = targetNode.downNode;
		while(true) {
			if (pointerNode == targetNode) {
				break;
			}
			// add particial solution
			solutions.add(pointerNode);
			
			// cover column nodes based on the right node of DLXNodes of target column node
			DLXNode rightSiblingNode = pointerNode.rightNode;
			while(true) {
				if (rightSiblingNode == pointerNode) {
					if (rightSiblingNode.headerNode.size == 0)
						rightSiblingNode.headerNode.coverNodes();
					break;
				}
				rightSiblingNode.headerNode.coverNodes();
				rightSiblingNode = rightSiblingNode.rightNode;
			}
			
			// Use the modified header nodes to find partial solutions recursively.
			if (solve(masterNode)) {
				return true;
				
			// if it returns false, it means that the partial solution is wrong,
			// it need to be uncovered.
			}else {
				solutions.remove(pointerNode);
				DLXNode leftSiblingNode = pointerNode.leftNode;
				while(true) {
					if (leftSiblingNode == pointerNode) {
						break;
					}
					leftSiblingNode.headerNode.uncoverNodes();
					leftSiblingNode = leftSiblingNode.leftNode;
				}
				targetNode.uncoverNodes();
				pointerNode = pointerNode.downNode;
			}
			
		}
		
		return false;
	}
    
    
    /**
     * Find the minimize sum of column node in the current matrix
     * 
     * @param masterNode master Node
     * @return the header node with mini-sum
     */
    private HeaderNode findColNodeWithMinSize(HeaderNode masterNode) {
		
		HeaderNode currentNode = null;
		HeaderNode targetNode = null;
		Integer min = null;
		while(true) {
			
			if (currentNode == null) {
				currentNode = targetNode = (HeaderNode) masterNode.rightNode;
				min = currentNode.size;
			}else {
				currentNode = (HeaderNode) currentNode.rightNode;
				if (currentNode == masterNode) {
					break;
				}
				if (min > currentNode.size) {
					targetNode = currentNode;
					min = currentNode.size;
				}
			}
		}
		
		return targetNode;
	}
    
    
    /**
     * To generate the dancing link board based on the matrix
     * @param matrixes the matrix
     * @return the master node
     */
    private HeaderNode makeDLXBoard(List<Matrix> matrixes) {
		
		HeaderNode masterNode = new HeaderNode(null);
		
		// link all the header node
		for (int idx = 0; idx < size; idx++) {
			HeaderNode colNode = new HeaderNode(idx);
			headerNodes.add(colNode);
			masterNode.setLeft(colNode);
		}
		
		masterNode.size = headerNodes.size();
		
		// link header node with cell node
		for (Matrix m : matrixes) {
			DLXNode prevNode = null;
			for (int idx = 0; idx < m.constraints.length; idx++) {
				if (deletedColumns.contains(idx)) {
					continue;
				}
				if (m.constraints[idx] != null) {
					HeaderNode colNode = headerNodes.get(idx);
					DLXNode newNode = new DLXNode(m.row, m.col, m.value, colNode);
					if (prevNode == null) {
						prevNode = newNode;
					}
					colNode.upNode.setDown(newNode);
					prevNode = prevNode.setRight(newNode);
					colNode.size++;
				}
			}
		}
		
		// pre-cover those nodes which have been inserted values
		for (Integer delIdx : deletedColumns) {
			headerNodes.get(delIdx).coverNodes();
		}
		
		masterNode.size = headerNodes.size() - deletedColumns.size();
		
		return masterNode;
		
	}
    
    
    /**
     * Remove the rows and columns if the cell contains a value
     * @param sudokuGrid the sudoku grid
     */
    private void removeRowsByGrid(SudokuGrid sudokuGrid) {
    	
    	for (int i = 0; i < sudokuGrid.size; i++) {
    		for (int j = 0; j < sudokuGrid.size; j++) {
    			if (sudokuGrid.grid[i][j] != null) {
    				// delete row by idx
    				for (Matrix m : matrixes) {
    					if (m.row == i && m.col == j && m.value == sudokuGrid.grid[i][j]) {
    						for (int k = 0; k < m.constraints.length; k++) {
    	    					if (m.constraints[k] != null && m.constraints[k] == 1) {
    	    						deletedColumns.add(k);
    	    					}
    	    				}
    						break;
    					}
    				}
    			}
    		}
    	}
	}

} // end of class DancingLinksSolver
